# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71f21f41102208e329687b8b4a9b2466b631d004b75c505a9cdb48dcbe2d9f160e95b319cbc6014dc7d16f350aaeb536993dbe2facaec3c599ecc5671a1e2cdc

test:
  secret_key_base: 96f7bb4e7714546cb4d86d263edd5bff9f82828c3c50c052e3f0d80a3c5ceeddaf9aedc03ffca2f49a747526db77e4b930cee0bc4e9ba91f0259589a8caa3922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
